version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - postgres
  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env